"""Im back

Revision ID: 0836d8d3d9a6
Revises: 778759510fdf
Create Date: 2023-07-01 23:45:25.910959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0836d8d3d9a6'
down_revision = '778759510fdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('token', sa.String(length=999), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    op.drop_column('users', 'branch_id')
    # ### end Alembic commands ###
