"""Initial migration

Revision ID: 30655a3182ec
Revises: 4a8dd8f68809
Create Date: 2023-08-08 12:29:02.490950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30655a3182ec'
down_revision = '4a8dd8f68809'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=999), nullable=True),
    sa.Column('body', sa.String(length=999), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
