"""Initial migration

Revision ID: 32b5262044e6
Revises: b91c8d68ee25
Create Date: 2023-08-05 13:43:26.208950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32b5262044e6'
down_revision = 'b91c8d68ee25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('warehouse_product_id', sa.Integer(), nullable=True))
    op.drop_column('contracts', 'customer_loc_id')
    op.drop_column('contracts', 'name')
    op.drop_column('customer_loc_products', 'name')
    op.add_column('customer_locations', sa.Column('address', sa.String(length=999), nullable=True))
    op.drop_column('customer_locations', 'adress')
    op.drop_column('expenses', 'type')
    op.drop_column('expenses', 'name')
    op.drop_column('incomes', 'type')
    op.drop_column('incomes', 'name')
    op.add_column('orders', sa.Column('date', sa.Date(), nullable=True))
    op.drop_column('orders', 'orienter')
    op.drop_column('orders', 'name')
    op.add_column('supplies', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.drop_column('supplies', 'name')
    op.drop_column('trades', 'name')
    op.add_column('transfers', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('transfers', sa.Column('warehouse_product_id', sa.Integer(), nullable=True))
    op.drop_column('transfers', 'product_id')
    op.drop_column('transfers', 'name')
    op.drop_column('user_products', 'name')
    op.drop_column('warehouses_products', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses_products', sa.Column('name', mysql.VARCHAR(length=999), nullable=True))
    op.add_column('user_products', sa.Column('name', mysql.VARCHAR(length=999), nullable=True))
    op.add_column('transfers', sa.Column('name', mysql.VARCHAR(length=999), nullable=True))
    op.add_column('transfers', sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('transfers', 'warehouse_product_id')
    op.drop_column('transfers', 'order_id')
    op.add_column('trades', sa.Column('name', mysql.VARCHAR(length=999), nullable=True))
    op.add_column('supplies', sa.Column('name', mysql.VARCHAR(length=999), nullable=True))
    op.drop_column('supplies', 'warehouse_id')
    op.add_column('orders', sa.Column('name', mysql.VARCHAR(length=999), nullable=True))
    op.add_column('orders', sa.Column('orienter', mysql.VARCHAR(length=999), nullable=True))
    op.drop_column('orders', 'date')
    op.add_column('incomes', sa.Column('name', mysql.VARCHAR(length=999), nullable=True))
    op.add_column('incomes', sa.Column('type', mysql.VARCHAR(length=999), nullable=True))
    op.add_column('expenses', sa.Column('name', mysql.VARCHAR(length=999), nullable=True))
    op.add_column('expenses', sa.Column('type', mysql.VARCHAR(length=999), nullable=True))
    op.add_column('customer_locations', sa.Column('adress', mysql.VARCHAR(length=999), nullable=True))
    op.drop_column('customer_locations', 'address')
    op.add_column('customer_loc_products', sa.Column('name', mysql.VARCHAR(length=999), nullable=True))
    op.add_column('contracts', sa.Column('name', mysql.VARCHAR(length=999), nullable=True))
    op.add_column('contracts', sa.Column('customer_loc_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('contracts', 'warehouse_product_id')
    # ### end Alembic commands ###
