"""Initial migration

Revision ID: 4a8dd8f68809
Revises: 32b5262044e6
Create Date: 2023-08-08 11:41:27.433699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8dd8f68809'
down_revision = '32b5262044e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
