"""Initial migration

Revision ID: 516b0db28797
Revises: 6b1946749e36
Create Date: 2023-08-14 09:19:07.896676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '516b0db28797'
down_revision = '6b1946749e36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('file', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
