"""Initial migration

Revision ID: 7316fe8548ff
Revises: f03996b0dfc9
Create Date: 2023-08-08 15:35:21.698230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7316fe8548ff'
down_revision = 'f03996b0dfc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
