"""Initial migration

Revision ID: b91c8d68ee25
Revises: 27c40220e058
Create Date: 2023-08-05 08:18:14.661560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b91c8d68ee25'
down_revision = '27c40220e058'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('name', sa.String(length=999), nullable=True))
    op.add_column('contracts', sa.Column('customer_loc_id', sa.Integer(), nullable=True))
    op.drop_column('contracts', 'warehouse_product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('warehouse_product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('contracts', 'customer_loc_id')
    op.drop_column('contracts', 'name')
    # ### end Alembic commands ###
