"""Initial migration

Revision ID: f03996b0dfc9
Revises: 30655a3182ec
Create Date: 2023-08-08 12:40:05.198148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03996b0dfc9'
down_revision = '30655a3182ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
