from db import Base
from models.users import Users
from models.branches import Branches
from models.categories import Categories
from models.contracts import Contracts
from models.customer_loc import Customer_loc_products
from models.customer_locations import Customer_locations
from models.customers import Customers
from models.expenses import Expenses
from models.incomes import Incomes
from models.kassa import Kassas
from models.orders import Orders
from models.phones import Phones
from models.products import Products
from models.supplies import Supplies
from models.trades import Trades
from models.transfers import Transfers
from models.uploaded_files import Uploaded
from models.user_products import User_products
from models.warehouse_products import Warehouses
